[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["en"]}

# Handle i18n routing
[[redirects]]
  from = "/:locale/*"
  to = "/:splat"
  status = 200
  force = false
  conditions = {Language = ["en"]}

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
