import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import "../globals.css";
import { Inter } from "next/font/google";
import Header from "../shared/header/Header";
import Footer from "../shared/Footer/Footer";
import ReduxProvider from "../providers/ReduxProvider";
import MobileTabs from "../shared/mobileTabs/MobileTabs";
import SideMenu from "../shared/header/SideMenu";
import CategoriesModal from "./(home)/components/categories/CategoriesModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={`font-${inter}`}>
        <ReduxProvider>
          <NextIntlClientProvider>
            <div className="relative">
              <Header />
              <SideMenu />
            </div>
            <main>{children}</main>
            <MobileTabs />
            <Footer />
            <CategoriesModal />
          </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
